export const formDefaultValues = {
    uniqueId: '',
    altId: '',
    givenName: '',
    lastName: '',
    gender: '',
    dob: '',
    address: '',
    street: '',
    city: '',
    state: '',
    zip: '',
    country: '',
    telephone: '',
    email: '',
    sendLetter: false,
    letterDate: '',
    comments: '',
};