export const forms = [
    {
        value: "dog",
        label: "Dog",
        address: "123 Dog St",
        altId: "DOG001",
        city: "Dogville",
        country: "USA",
        dob: "2024-09-26",
        email: "max@dogmail.com",
        gender: "Male",
        givenName: "Max",
        lastName: "Barkington",
        state: "CA",
        street: "Woof Ave",
        telephone: "555-1234",
        uniqueId: "12345",
        zip: "90210"
    },
    {
        value: 'cat',
        label: 'Cat',
        uniqueId: '54321',
        altId: 'CAT002',
        givenName: 'Whiskers',
        lastName: 'Feline',
        gender: 'Female',
        dob: '2018-07-21',
        address: '456 Cat Blvd',
        street: 'Purr Lane',
        city: 'Cat City',
        state: 'NY',
        zip: '10001',
        country: 'USA',
        telephone: '555-5678',
        email: 'whiskers@catmail.com',
    },
    {
        value: 'hamster',
        label: 'Hamster',
        uniqueId: '67890',
        altId: 'HAM003',
        givenName: 'Nibbles',
        lastName: 'Rodentia',
        gender: 'Male',
        dob: '2021-01-11',
        address: '789 Hamster Ct',
        street: 'Cheese St',
        city: 'Hamstertown',
        state: 'FL',
        zip: '33101',
        country: 'USA',
        telephone: '555-4321',
        email: 'nibbles@hamstermail.com',
    },
];

export const genders = [
    { label: "Male", value: "male" },
    { label: "Female", value: "female" },
    { label: "Non-binary", value: "non-binary" },
    { label: "Genderqueer", value: "genderqueer" },
    { label: "Genderfluid", value: "genderfluid" },
    { label: "Agender", value: "agender" },
    { label: "Bigender", value: "bigender" },
    { label: "Two-Spirit", value: "two-spirit" },
    { label: "Transgender Male", value: "transgender-male" },
    { label: "Transgender Female", value: "transgender-female" },
    { label: "Pangender", value: "pangender" },
    { label: "Other", value: "other" },
];

export const states = [
    { name: "Alabama", abbreviation: "AL" },
    { name: "Alaska", abbreviation: "AK" },
    { name: "Arizona", abbreviation: "AZ" },
    { name: "Arkansas", abbreviation: "AR" },
    { name: "California", abbreviation: "CA" },
    { name: "Colorado", abbreviation: "CO" },
    { name: "Connecticut", abbreviation: "CT" },
    { name: "Delaware", abbreviation: "DE" },
    { name: "Florida", abbreviation: "FL" },
    { name: "Georgia", abbreviation: "GA" },
    { name: "Hawaii", abbreviation: "HI" },
    { name: "Idaho", abbreviation: "ID" },
    { name: "Illinois", abbreviation: "IL" },
    { name: "Indiana", abbreviation: "IN" },
    { name: "Iowa", abbreviation: "IA" },
    { name: "Kansas", abbreviation: "KS" },
    { name: "Kentucky", abbreviation: "KY" },
    { name: "Louisiana", abbreviation: "LA" },
    { name: "Maine", abbreviation: "ME" },
    { name: "Maryland", abbreviation: "MD" },
    { name: "Massachusetts", abbreviation: "MA" },
    { name: "Michigan", abbreviation: "MI" },
    { name: "Minnesota", abbreviation: "MN" },
    { name: "Mississippi", abbreviation: "MS" },
    { name: "Missouri", abbreviation: "MO" },
    { name: "Montana", abbreviation: "MT" },
    { name: "Nebraska", abbreviation: "NE" },
    { name: "Nevada", abbreviation: "NV" },
    { name: "New Hampshire", abbreviation: "NH" },
    { name: "New Jersey", abbreviation: "NJ" },
    { name: "New Mexico", abbreviation: "NM" },
    { name: "New York", abbreviation: "NY" },
    { name: "North Carolina", abbreviation: "NC" },
    { name: "North Dakota", abbreviation: "ND" },
    { name: "Ohio", abbreviation: "OH" },
    { name: "Oklahoma", abbreviation: "OK" },
    { name: "Oregon", abbreviation: "OR" },
    { name: "Pennsylvania", abbreviation: "PA" },
    { name: "Rhode Island", abbreviation: "RI" },
    { name: "South Carolina", abbreviation: "SC" },
    { name: "South Dakota", abbreviation: "SD" },
    { name: "Tennessee", abbreviation: "TN" },
    { name: "Texas", abbreviation: "TX" },
    { name: "Utah", abbreviation: "UT" },
    { name: "Vermont", abbreviation: "VT" },
    { name: "Virginia", abbreviation: "VA" },
    { name: "Washington", abbreviation: "WA" },
    { name: "West Virginia", abbreviation: "WV" },
    { name: "Wisconsin", abbreviation: "WI" },
    { name: "Wyoming", abbreviation: "WY" }
];

export const countries = [
    { name: "Afghanistan", abbreviation: "AF" },
    { name: "Albania", abbreviation: "AL" },
    { name: "Algeria", abbreviation: "DZ" },
    { name: "Andorra", abbreviation: "AD" },
    { name: "Angola", abbreviation: "AO" },
    { name: "Antigua and Barbuda", abbreviation: "AG" },
    { name: "Argentina", abbreviation: "AR" },
    { name: "Armenia", abbreviation: "AM" },
    { name: "Australia", abbreviation: "AU" },
    { name: "Austria", abbreviation: "AT" },
    { name: "Azerbaijan", abbreviation: "AZ" },
    { name: "Bahamas", abbreviation: "BS" },
    { name: "Bahrain", abbreviation: "BH" },
    { name: "Bangladesh", abbreviation: "BD" },
    { name: "Barbados", abbreviation: "BB" },
    { name: "Belarus", abbreviation: "BY" },
    { name: "Belgium", abbreviation: "BE" },
    { name: "Belize", abbreviation: "BZ" },
    { name: "Benin", abbreviation: "BJ" },
    { name: "Bhutan", abbreviation: "BT" },
    { name: "Bolivia", abbreviation: "BO" },
    { name: "Bosnia and Herzegovina", abbreviation: "BA" },
    { name: "Botswana", abbreviation: "BW" },
    { name: "Brazil", abbreviation: "BR" },
    { name: "Brunei", abbreviation: "BN" },
    { name: "Bulgaria", abbreviation: "BG" },
    { name: "Burkina Faso", abbreviation: "BF" },
    { name: "Burundi", abbreviation: "BI" },
    { name: "Cabo Verde", abbreviation: "CV" },
    { name: "Cambodia", abbreviation: "KH" },
    { name: "Cameroon", abbreviation: "CM" },
    { name: "Canada", abbreviation: "CA" },
    { name: "Central African Republic", abbreviation: "CF" },
    { name: "Chad", abbreviation: "TD" },
    { name: "Chile", abbreviation: "CL" },
    { name: "China", abbreviation: "CN" },
    { name: "Colombia", abbreviation: "CO" },
    { name: "Comoros", abbreviation: "KM" },
    { name: "Congo, Republic of the", abbreviation: "CG" },
    { name: "Congo, Democratic Republic of the", abbreviation: "CD" },
    { name: "Costa Rica", abbreviation: "CR" },
    { name: "Croatia", abbreviation: "HR" },
    { name: "Cuba", abbreviation: "CU" },
    { name: "Cyprus", abbreviation: "CY" },
    { name: "Czech Republic", abbreviation: "CZ" },
    { name: "Denmark", abbreviation: "DK" },
    { name: "Djibouti", abbreviation: "DJ" },
    { name: "Dominica", abbreviation: "DM" },
    { name: "Dominican Republic", abbreviation: "DO" },
    { name: "Ecuador", abbreviation: "EC" },
    { name: "Egypt", abbreviation: "EG" },
    { name: "El Salvador", abbreviation: "SV" },
    { name: "Equatorial Guinea", abbreviation: "GQ" },
    { name: "Eritrea", abbreviation: "ER" },
    { name: "Estonia", abbreviation: "EE" },
    { name: "Eswatini", abbreviation: "SZ" },
    { name: "Ethiopia", abbreviation: "ET" },
    { name: "Fiji", abbreviation: "FJ" },
    { name: "Finland", abbreviation: "FI" },
    { name: "France", abbreviation: "FR" },
    { name: "Gabon", abbreviation: "GA" },
    { name: "Gambia", abbreviation: "GM" },
    { name: "Georgia", abbreviation: "GE" },
    { name: "Germany", abbreviation: "DE" },
    { name: "Ghana", abbreviation: "GH" },
    { name: "Greece", abbreviation: "GR" },
    { name: "Grenada", abbreviation: "GD" },
    { name: "Guatemala", abbreviation: "GT" },
    { name: "Guinea", abbreviation: "GN" },
    { name: "Guinea-Bissau", abbreviation: "GW" },
    { name: "Guyana", abbreviation: "GY" },
    { name: "Haiti", abbreviation: "HT" },
    { name: "Honduras", abbreviation: "HN" },
    { name: "Hungary", abbreviation: "HU" },
    { name: "Iceland", abbreviation: "IS" },
    { name: "India", abbreviation: "IN" },
    { name: "Indonesia", abbreviation: "ID" },
    { name: "Iran", abbreviation: "IR" },
    { name: "Iraq", abbreviation: "IQ" },
    { name: "Ireland", abbreviation: "IE" },
    { name: "Israel", abbreviation: "IL" },
    { name: "Italy", abbreviation: "IT" },
    { name: "Jamaica", abbreviation: "JM" },
    { name: "Japan", abbreviation: "JP" },
    { name: "Jordan", abbreviation: "JO" },
    { name: "Kazakhstan", abbreviation: "KZ" },
    { name: "Kenya", abbreviation: "KE" },
    { name: "Kiribati", abbreviation: "KI" },
    { name: "Korea, North", abbreviation: "KP" },
    { name: "Korea, South", abbreviation: "KR" },
    { name: "Kuwait", abbreviation: "KW" },
    { name: "Kyrgyzstan", abbreviation: "KG" },
    { name: "Laos", abbreviation: "LA" },
    { name: "Latvia", abbreviation: "LV" },
    { name: "Lebanon", abbreviation: "LB" },
    { name: "Lesotho", abbreviation: "LS" },
    { name: "Liberia", abbreviation: "LR" },
    { name: "Libya", abbreviation: "LY" },
    { name: "Liechtenstein", abbreviation: "LI" },
    { name: "Lithuania", abbreviation: "LT" },
    { name: "Luxembourg", abbreviation: "LU" },
    { name: "Madagascar", abbreviation: "MG" },
    { name: "Malawi", abbreviation: "MW" },
    { name: "Malaysia", abbreviation: "MY" },
    { name: "Maldives", abbreviation: "MV" },
    { name: "Mali", abbreviation: "ML" },
    { name: "Malta", abbreviation: "MT" },
    { name: "Marshall Islands", abbreviation: "MH" },
    { name: "Mauritania", abbreviation: "MR" },
    { name: "Mauritius", abbreviation: "MU" },
    { name: "Mexico", abbreviation: "MX" },
    { name: "Micronesia", abbreviation: "FM" },
    { name: "Moldova", abbreviation: "MD" },
    { name: "Monaco", abbreviation: "MC" },
    { name: "Mongolia", abbreviation: "MN" },
    { name: "Montenegro", abbreviation: "ME" },
    { name: "Morocco", abbreviation: "MA" },
    { name: "Mozambique", abbreviation: "MZ" },
    { name: "Myanmar", abbreviation: "MM" },
    { name: "Namibia", abbreviation: "NA" },
    { name: "Nauru", abbreviation: "NR" },
    { name: "Nepal", abbreviation: "NP" },
    { name: "Netherlands", abbreviation: "NL" },
    { name: "New Zealand", abbreviation: "NZ" },
    { name: "Nicaragua", abbreviation: "NI" },
    { name: "Niger", abbreviation: "NE" },
    { name: "Nigeria", abbreviation: "NG" },
    { name: "North Macedonia", abbreviation: "MK" },
    { name: "Norway", abbreviation: "NO" },
    { name: "Oman", abbreviation: "OM" },
    { name: "Pakistan", abbreviation: "PK" },
    { name: "Palau", abbreviation: "PW" },
    { name: "Palestine", abbreviation: "PS" },
    { name: "Panama", abbreviation: "PA" },
    { name: "Papua New Guinea", abbreviation: "PG" },
    { name: "Paraguay", abbreviation: "PY" },
    { name: "Peru", abbreviation: "PE" },
    { name: "Philippines", abbreviation: "PH" },
    { name: "Poland", abbreviation: "PL" },
    { name: "Portugal", abbreviation: "PT" },
    { name: "Qatar", abbreviation: "QA" },
    { name: "Romania", abbreviation: "RO" },
    { name: "Russia", abbreviation: "RU" },
    { name: "Rwanda", abbreviation: "RW" },
    { name: "Saint Kitts and Nevis", abbreviation: "KN" },
    { name: "Saint Lucia", abbreviation: "LC" },
    { name: "Saint Vincent and the Grenadines", abbreviation: "VC" },
    { name: "Samoa", abbreviation: "WS" },
    { name: "San Marino", abbreviation: "SM" },
    { name: "Sao Tome and Principe", abbreviation: "ST" },
    { name: "Saudi Arabia", abbreviation: "SA" },
    { name: "Senegal", abbreviation: "SN" },
    { name: "Serbia", abbreviation: "RS" },
    { name: "Seychelles", abbreviation: "SC" },
    { name: "Sierra Leone", abbreviation: "SL" },
    { name: "Singapore", abbreviation: "SG" },
    { name: "Slovakia", abbreviation: "SK" },
    { name: "Slovenia", abbreviation: "SI" },
    { name: "Solomon Islands", abbreviation: "SB" },
    { name: "Somalia", abbreviation: "SO" },
    { name: "South Africa", abbreviation: "ZA" },
    { name: "South Sudan", abbreviation: "SS" },
    { name: "Spain", abbreviation: "ES" },
    { name: "Sri Lanka", abbreviation: "LK" },
    { name: "Sudan", abbreviation: "SD" },
    { name: "Suriname", abbreviation: "SR" },
    { name: "Sweden", abbreviation: "SE" },
    { name: "Switzerland", abbreviation: "CH" },
    { name: "Syria", abbreviation: "SY" },
    { name: "Taiwan", abbreviation: "TW" },
    { name: "Tajikistan", abbreviation: "TJ" },
    { name: "Tanzania", abbreviation: "TZ" },
    { name: "Thailand", abbreviation: "TH" },
    { name: "Timor-Leste", abbreviation: "TL" },
    { name: "Togo", abbreviation: "TG" },
    { name: "Tonga", abbreviation: "TO" },
    { name: "Trinidad and Tobago", abbreviation: "TT" },
    { name: "Tunisia", abbreviation: "TN" },
    { name: "Turkey", abbreviation: "TR" },
    { name: "Turkmenistan", abbreviation: "TM" },
    { name: "Tuvalu", abbreviation: "TV" },
    { name: "Uganda", abbreviation: "UG" },
    { name: "Ukraine", abbreviation: "UA" },
    { name: "United Arab Emirates", abbreviation: "AE" },
    { name: "United Kingdom", abbreviation: "GB" },
    { name: "United States", abbreviation: "US" },
    { name: "Uruguay", abbreviation: "UY" },
    { name: "Uzbekistan", abbreviation: "UZ" },
    { name: "Vanuatu", abbreviation: "VU" },
    { name: "Vatican City", abbreviation: "VA" },
    { name: "Venezuela", abbreviation: "VE" },
    { name: "Vietnam", abbreviation: "VN" },
    { name: "Yemen", abbreviation: "YE" },
    { name: "Zambia", abbreviation: "ZM" },
    { name: "Zimbabwe", abbreviation: "ZW" },
];